;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2016/3/25 10:30:12

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1001	1001	; index index.html
#define IDH_1000	1000	; index ex index ex\index ex.html
#define IDH_1002	1002	; ButtonAuto web\ButtonAuto.html
#define IDH_1003	1003	; ImageButton web\ImageButton .html
#define IDH_1004	1004	; layout web\layout.html
#define IDH_1005	1005	; lenList yuan web\lenList yuan.html
#define IDH_1006	1006	; lenList zi 4.01t web\lenList zi 4.01t.html
#define IDH_1007	1007	; lenList zi x web\lenList zi x.html
#define IDH_1008	1008	; nav yuan web\nav yuan.html
#define IDH_1009	1009	; nav zi web\nav zi.html
