;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2016/3/25 10:30:12

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1001=index.html	; index
IDH_1000=index ex\index ex.html	; index ex
IDH_1002=web\ButtonAuto.html	; ButtonAuto
IDH_1003=web\ImageButton .html	; ImageButton
IDH_1004=web\layout.html	; layout
IDH_1005=web\lenList yuan.html	; lenList yuan
IDH_1006=web\lenList zi 4.01t.html	; lenList zi 4.01t
IDH_1007=web\lenList zi x.html	; lenList zi x
IDH_1008=web\nav yuan.html	; nav yuan
IDH_1009=web\nav zi.html	; nav zi
